/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import beans.Employee;
import beans.Gender;
import bl.EmployeeListModel;
import db.DB_Access;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import utils.IOHandler;

/**
 *
 * @author martin
 */
public class MainGUI extends javax.swing.JFrame {

    private DB_Access access;
    private EmployeeListModel elm;
    private boolean isConnected = true;
    private Gender selectedGender = Gender.Male;

    /**
     * Creates new form MainGUI
     */
    public MainGUI() throws SQLException, ClassNotFoundException, FileNotFoundException {
        initComponents();
        this.access = new DB_Access();
        this.lbDB.setText("Database: mitarbeiterdb");
        this.elm = new EmployeeListModel(this.access.getEmployees());
        this.lE.setModel(elm);
        this.setDepartments();
        this.updateAVG();
    }

    public void setDepartments() {
        this.cbAb.removeAllItems();
        this.cbAb.addItem("Alle");
        this.elm.getDepartments().forEach(dep -> this.cbAb.addItem(dep + ""));
    }

    private void updateAVG() throws SQLException {
        this.lbAVG.setText(String.format("%.2f €", this.access.getAverageSalery(selectedGender)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        DeleteMenu = new javax.swing.JPopupMenu();
        itemDelete = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        lbDB = new javax.swing.JLabel();
        btConn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ipName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ipVorname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ipGebDat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ipGehalt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ipAbt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbGeAd = new javax.swing.JComboBox<>();
        btAdd = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbAb = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lE = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbGe = new javax.swing.JComboBox<>();
        lbAVG = new javax.swing.JLabel();

        itemDelete.setText("Delete User");
        itemDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDeleteEmployee(evt);
            }
        });
        DeleteMenu.add(itemDelete);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Add"));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 5, 0};
        jPanel1Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel1.setLayout(jPanel1Layout);

        lbDB.setText("Database: none");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(lbDB, gridBagConstraints);

        btConn.setText("Disconnect");
        btConn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDBDC(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(btConn, gridBagConstraints);

        jLabel2.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel2, gridBagConstraints);

        ipName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(ipName, gridBagConstraints);

        jLabel3.setText("Vorname");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(ipVorname, gridBagConstraints);

        jLabel4.setText("Geb. Datum");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 11);
        jPanel1.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(ipGebDat, gridBagConstraints);

        jLabel5.setText("Gehalt");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(ipGehalt, gridBagConstraints);

        jLabel6.setText("Abteilung");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(ipAbt, gridBagConstraints);

        jLabel7.setText("Geschlecht");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel7, gridBagConstraints);

        cbGeAd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Männlich", "Weiblich" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(cbGeAd, gridBagConstraints);

        btAdd.setText("ADD");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAddEmployee(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(btAdd, gridBagConstraints);

        getContentPane().add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Manage"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        jLabel8.setText("Abteilung");
        jPanel3.add(jLabel8);

        cbAb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAbActionPerformed(evt);
            }
        });
        jPanel3.add(cbAb);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        lE.setFont(new java.awt.Font("Droid Sans Mono", 1, 12)); // NOI18N
        lE.setComponentPopupMenu(DeleteMenu);
        jScrollPane1.setViewportView(lE);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.setFont(new java.awt.Font("Droid Sans Mono", 0, 12)); // NOI18N
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Geschlecht");
        jPanel4.add(jLabel1, new java.awt.GridBagConstraints());

        cbGe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Männlich", "Weiblich" }));
        cbGe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onGenderShowSelect(evt);
            }
        });
        jPanel4.add(cbGe, new java.awt.GridBagConstraints());

        lbAVG.setText("AVG:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(lbAVG, gridBagConstraints);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ipNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipNameActionPerformed

    private void onDBDC(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onDBDC
        try {

            if (this.isConnected) {
                this.access.disconnect();
                this.lbDB.setText("Database: none");
                this.btAdd.setEnabled(false);
                this.itemDelete.setEnabled(false);
                this.cbAb.setEnabled(false);
                this.cbGe.setEnabled(false);
                this.btConn.setText("Connect");
                this.isConnected = false;
            } else {
                this.access.connect();
                this.access.setupStatements();
                this.lbDB.setText("Database: mitarbeiterdb");
                this.btAdd.setEnabled(true);
                this.itemDelete.setEnabled(true);
                this.cbAb.setEnabled(true);
                this.cbGe.setEnabled(true);
                this.btConn.setText("Disconnect");
                this.isConnected = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_onDBDC

    private void cbAbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAbActionPerformed
        try {
            String filter = (String) this.cbAb.getSelectedItem();
            if (filter != null) {
                this.elm.setFilter(filter);
                this.updateAVG();
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbAbActionPerformed

    private void onGenderShowSelect(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onGenderShowSelect
        try {
            if (((String) this.cbGe.getSelectedItem()).equals("Männlich")) {
                this.selectedGender = Gender.Male;
            } else {
                this.selectedGender = Gender.Female;
            }
            this.updateAVG();
        } catch (SQLException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_onGenderShowSelect

    private void onAddEmployee(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAddEmployee
        try {
            String name = this.ipName.getText();
            String vorname = this.ipVorname.getText();
            LocalDate geb = LocalDate.parse(this.ipGebDat.getText(), Employee.DTF);
            double gehalt = Double.parseDouble(this.ipGehalt.getText());
            int abteilung = Integer.parseInt(this.ipAbt.getText());
            Gender geschlecht = ((String) this.cbGeAd.getSelectedItem()).equals("Männlich") ? Gender.Male : Gender.Female;
            Employee e = new Employee(name, vorname, geb, gehalt, abteilung, geschlecht);
            if (this.access.insertEmployee(e)) { // successfully inserted --> add it to the displayed list
                this.elm.addEmployee(e);
                this.setDepartments();
                this.updateAVG();
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_onAddEmployee

    private void onDeleteEmployee(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onDeleteEmployee
        try {
            Employee e = this.lE.getSelectedValue();
            this.access.removeEmployee(e);
            this.elm.removeEmployee(e);
            this.setDepartments();
            this.updateAVG();
        } catch (SQLException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_onDeleteEmployee

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainGUI().setVisible(true);
                } catch (SQLException | ClassNotFoundException | FileNotFoundException ex) {
                    System.out.println("ooops");
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu DeleteMenu;
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btConn;
    private javax.swing.JComboBox<String> cbAb;
    private javax.swing.JComboBox<String> cbGe;
    private javax.swing.JComboBox<String> cbGeAd;
    private javax.swing.JTextField ipAbt;
    private javax.swing.JTextField ipGebDat;
    private javax.swing.JTextField ipGehalt;
    private javax.swing.JTextField ipName;
    private javax.swing.JTextField ipVorname;
    private javax.swing.JMenuItem itemDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Employee> lE;
    private javax.swing.JLabel lbAVG;
    private javax.swing.JLabel lbDB;
    // End of variables declaration//GEN-END:variables
}
